// comment
console.log("Hello World!")
console.log("Hello World!")
console.log("Second")
console.log("day1")
console.log("day2")
console.log("day3")
console.log("day4")
console.log("day5")
console.log("day6")
console.log("day7")
console.log("day8")
console.log("day9")
console.log("day10")
console.log("day11")
console.log("day12")
console.log("day13")
console.log("day14")
console.log("day15")
console.log("day16")
console.log("day17")
https://docs.google.com/presentation/d/186UqFbQQHPn6oMRfapDxmLUQf2KF9l8Y/edit?usp=drivesdk&ouid=101717357944039148445&rtpof=true&sd=true
